/* =====================================================================
   IS IT WORTH IT? — front-end renderer
   Reads window.DATA (generated by scripts/update_data.py) and paints the board.
   ===================================================================== */
(function () {
  "use strict";

  var DATA = window.DATA;
  if (!DATA) {
    document.getElementById("card-grid").innerHTML =
      '<p class="panel">DATA NOT LOADED. Run <code>python scripts/update_data.py</code> first.</p>';
    return;
  }

  var ACCENT = { "WORTH IT": "var(--worth)", "SOLID": "var(--solid)", "MEH": "var(--meh)", "OVERPRICED": "var(--bad)", "FREE TIER": "var(--purple)" };
  var VERDICT_CLASS = { "WORTH IT": "worth", "SOLID": "solid", "MEH": "meh", "OVERPRICED": "bad", "FREE TIER": "solid" };

  var state = { category: DATA.categories[0].id, sort: "cwi" };

  /* ---------- helpers ---------- */
  function el(tag, cls, html) {
    var n = document.createElement(tag);
    if (cls) n.className = cls;
    if (html != null) n.innerHTML = html;
    return n;
  }
  function esc(s) {
    return String(s).replace(/[&<>"]/g, function (c) {
      return { "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" }[c];
    });
  }
  function fmtWeek(iso) {
    if (!iso) return "————";
    var p = iso.split("-");
    var months = ["JAN","FEB","MAR","APR","MAY","JUN","JUL","AUG","SEP","OCT","NOV","DEC"];
    return months[parseInt(p[1], 10) - 1] + " " + parseInt(p[2], 10) + ", " + p[0];
  }

  /* ---------- stamps ---------- */
  document.getElementById("week-stamp").textContent = "WEEK OF " + fmtWeek(DATA.meta.weekOf);
  document.getElementById("gen-stamp").textContent = "GENERATED " + fmtWeek(DATA.meta.weekOf);

  /* ---------- live API token-price band ---------- */
  (function () {
    var band = document.getElementById("live-band");
    var models = DATA.apiModels || [];
    if (!band) return;
    if (!models.length) { band.style.display = "none"; return; }
    var head = el("div", "liveband-head",
      "LIVE API TOKEN PRICES <span class='lb-sub'>per 1M tokens · checked " +
      fmtWeek(DATA.meta.priceCheckedAt || DATA.meta.weekOf) + "</span>");
    band.appendChild(head);
    var row = el("div", "liveband-row");
    models.forEach(function (m) {
      var dot = m.status && m.status.indexOf("live") === 0 ? "live" : "verified";
      var chip = el("div", "lb-chip");
      chip.innerHTML =
        "<span class='lb-dot " + dot + "'></span>" +
        "<span class='lb-name'>" + esc(m.label) + "</span>" +
        "<span class='lb-px'>in $" + m.inputPerM + " · out $" + m.outputPerM + "</span>";
      row.appendChild(chip);
    });
    band.appendChild(row);
  })();

  /* ---------- category tabs ---------- */
  var tabs = document.getElementById("cat-tabs");
  tabs.appendChild(el("span", "control-label", "CATEGORY"));
  DATA.categories.forEach(function (c) {
    var b = el("button", "pixbtn cat-btn" + (c.id === state.category ? " active" : ""), esc(c.name.toUpperCase()));
    b.setAttribute("data-cat", c.id);
    b.addEventListener("click", function () {
      state.category = c.id;
      syncTabs(); render();
    });
    tabs.appendChild(b);
  });
  function syncTabs() {
    [].forEach.call(tabs.querySelectorAll(".cat-btn"), function (b) {
      b.classList.toggle("active", b.getAttribute("data-cat") === state.category);
    });
  }

  /* ---------- sort buttons ---------- */
  [].forEach.call(document.querySelectorAll(".sort-btn"), function (b) {
    b.addEventListener("click", function () {
      state.sort = b.getAttribute("data-sort");
      [].forEach.call(document.querySelectorAll(".sort-btn"), function (x) {
        x.classList.toggle("active", x === b);
      });
      render();
    });
  });

  /* ---------- card builder ---------- */
  function buildMeter(cwi) {
    var on = Math.round((cwi / 100) * 20);
    var m = el("div", "meter");
    for (var i = 0; i < 20; i++) m.appendChild(el("span", "seg" + (i < on ? " on" : "")));
    return m;
  }

  function buildSpark(history) {
    var wrap = el("div", "spark");
    var pts = history.slice(-6);
    var vals = pts.map(function (h) { return h.cwi; });
    var min = Math.min.apply(null, vals), max = Math.max.apply(null, vals);
    var span = Math.max(1, max - min);
    pts.forEach(function (h) {
      var bar = el("span", "bar");
      bar.style.height = (8 + ((h.cwi - min) / span) * 26) + "px";
      bar.title = h.week + " · CWI " + h.cwi;
      wrap.appendChild(bar);
    });
    return { node: wrap, first: vals[0], last: vals[vals.length - 1] };
  }

  var PROV = {
    "live":         { cls: "live",     txt: "● LIVE" },
    "live-changed": { cls: "live",     txt: "● LIVE ↻" },
    "verified":     { cls: "verified", txt: "✓ VERIFIED" },
    "review":       { cls: "review",   txt: "⚠ REVIEW" },
    "unreachable":  { cls: "review",   txt: "✕ OFFLINE" },
    "manual":       { cls: "manual",   txt: "EST." }
  };
  function buildProvenance(s) {
    var p = PROV[s.priceStatus] || PROV.manual;
    var wrap = el("div", "provenance");
    var badge = el("span", "prov " + p.cls, p.txt);
    wrap.appendChild(badge);
    if (s.priceCheckedAt) wrap.appendChild(el("span", "prov-date", "checked " + fmtWeek(s.priceCheckedAt)));
    if (s.priceSource) {
      var a = el("a", "prov-src", "src");
      a.href = s.priceSource; a.target = "_blank"; a.rel = "noopener";
      a.title = s.priceSource;
      wrap.appendChild(a);
    }
    return wrap;
  }

  function buildCard(s) {
    var accent = ACCENT[s.verdict] || "var(--green)";
    var card = el("div", "card");
    card.style.setProperty("--card-accent", accent);

    /* top: rank + vendor/name + plan */
    var top = el("div", "card-top");
    var idblock = el("div");
    idblock.appendChild(el("div", "vendor", esc(s.vendor)));
    idblock.appendChild(el("div", "svc-name", esc(s.name)));
    idblock.appendChild(el("div", "svc-plan", esc(s.plan)));
    top.appendChild(idblock);
    top.appendChild(el("div", "rank-badge", "#" + (s.rank || "-") + " IN " + catName(s.category).toUpperCase()));
    card.appendChild(top);

    /* price + provenance */
    var price = el("div", "price-row");
    price.appendChild(el("span", "price", "$" + s.priceMonthly));
    price.appendChild(el("span", "price-unit", "/ month"));
    card.appendChild(price);
    card.appendChild(buildProvenance(s));

    /* worth meter */
    var ml = el("div", "meter-label");
    ml.appendChild(el("span", null, "WORTH METER"));
    ml.appendChild(el("span", "cwi-num", "CWI " + s.cwi));
    card.appendChild(ml);
    card.appendChild(buildMeter(s.cwi));

    /* verdict + value/$ */
    var vrow = el("div", "trend");
    vrow.appendChild(el("div", "verdict", esc(s.verdict)));
    if (s.valuePerDollar != null) {
      vrow.appendChild(el("div", "delta flat", catUnit(s.category) + ": " + s.valuePerDollar + "/$"));
    }
    card.appendChild(vrow);

    /* notes */
    var notes = el("div", "notes");
    var best = el("div", "note best");
    best.appendChild(el("span", "tag", "BEST FOR"));
    best.appendChild(el("span", "txt", esc(s.bestFor)));
    notes.appendChild(best);
    var weak = el("div", "note weak");
    weak.appendChild(el("span", "tag", "WATCH OUT"));
    weak.appendChild(el("span", "txt", esc(s.weakness)));
    notes.appendChild(weak);
    card.appendChild(notes);

    /* trend */
    if (s.history && s.history.length > 1) {
      var trend = el("div", "trend");
      var sp = buildSpark(s.history);
      trend.appendChild(sp.node);
      var d = sp.last - sp.first;
      var cls = d > 0 ? "up" : d < 0 ? "down" : "flat";
      var arrow = d > 0 ? "▲" : d < 0 ? "▼" : "►";
      trend.appendChild(el("div", "delta " + cls, arrow + " " + (d > 0 ? "+" : "") + d + " /6wk"));
      card.appendChild(trend);
    }

    /* link */
    if (s.link) {
      var a = el("a", "card-link", "VIEW PRICING");
      a.href = s.link; a.target = "_blank"; a.rel = "noopener";
      card.appendChild(a);
    }
    return card;
  }

  /* ---------- category lookups ---------- */
  function catObj(id) { return DATA.categories.filter(function (c) { return c.id === id; })[0] || {}; }
  function catName(id) { return (catObj(id).name || id); }
  function catUnit(id) { return (catObj(id).valueLabel || "value"); }

  /* ---------- render ---------- */
  function render() {
    var grid = document.getElementById("card-grid");
    grid.innerHTML = "";

    document.getElementById("cat-blurb").textContent = "» " + (catObj(state.category).blurb || "");

    var list = DATA.services.filter(function (s) { return s.category === state.category && s.cwi != null; });
    list.sort(function (a, b) {
      if (state.sort === "price") return a.priceMonthly - b.priceMonthly;
      if (state.sort === "value") return (b.valuePerDollar || 0) - (a.valuePerDollar || 0);
      return b.cwi - a.cwi; // worth
    });

    list.forEach(function (s) { grid.appendChild(buildCard(s)); });
  }

  render();
})();
